services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - kidneyapp-minio-staging:/data

volumes:
  kidneyapp-minio-staging:
    external: true
